/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;




import Modelo.PrcedimientosBD;

import Controlador.ProcedimientosMAtlab;



import java.awt.Dimension;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
   import java.io.*;
   import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.jfree.chart.ChartPanel;

/**
 *
 * @author alez
 */
public class Panel_Principal_1 extends javax.swing.JFrame {

    /**
     * Creates new form Panel_Principal
     */
    public Panel_Principal_1() {
         
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_ImagenUsuarios = new javax.swing.JFrame();
        javax.swing.JLabel ImagenUsuarios = new javax.swing.JLabel();
        jFrame_AdvertenciaSumaCantidad = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        ConsumoE = new javax.swing.JCheckBox();
        ImpactoCurva = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Cantidad_PHEV = new javax.swing.JComboBox();
        Cantidad_BEV = new javax.swing.JComboBox();
        Cantidad_PHEV1 = new javax.swing.JComboBox();
        Cantidad_BEV1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        TiposUSR_PHEV = new javax.swing.JComboBox();
        TiposUSR_BEV = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        TiposEV_PHEV1 = new javax.swing.JComboBox();
        TiposEV_BEV1 = new javax.swing.JComboBox();
        TiposEV_BEV = new javax.swing.JComboBox();
        TiposEV_PHEV = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1_anioSimular = new javax.swing.JTextField();
        jSlider3_anioSimulacion = new javax.swing.JSlider();
        jSlider2_CantidadVehiculos = new javax.swing.JSlider();
        jTextField13_CantidadVehiculos = new javax.swing.JTextField();
        jButton4_GraficarMatlab = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_CasoSimular = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Esenario_ImpactoAmb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jSlider4_anioImpactoAmbiental = new javax.swing.JSlider();
        Tiempo_ImpactoAmb = new javax.swing.JTextField();
        BottonImpactoAmb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jFrame_ImagenUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_ImagenUsuarios.setFocusTraversalPolicyProvider(true);

        ImagenUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CxnTiposUsuarios.jpg"))); // NOI18N

        javax.swing.GroupLayout jFrame_ImagenUsuariosLayout = new javax.swing.GroupLayout(jFrame_ImagenUsuarios.getContentPane());
        jFrame_ImagenUsuarios.getContentPane().setLayout(jFrame_ImagenUsuariosLayout);
        jFrame_ImagenUsuariosLayout.setHorizontalGroup(
            jFrame_ImagenUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_ImagenUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenUsuarios)
                .addContainerGap())
        );
        jFrame_ImagenUsuariosLayout.setVerticalGroup(
            jFrame_ImagenUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_ImagenUsuariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ImagenUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jFrame_AdvertenciaSumaCantidad.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_AdvertenciaSumaCantidad.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdvertenciaTexto.png"))); // NOI18N
        jLabel22.setText("jLabel22");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22)
        );

        javax.swing.GroupLayout jFrame_AdvertenciaSumaCantidadLayout = new javax.swing.GroupLayout(jFrame_AdvertenciaSumaCantidad.getContentPane());
        jFrame_AdvertenciaSumaCantidad.getContentPane().setLayout(jFrame_AdvertenciaSumaCantidadLayout);
        jFrame_AdvertenciaSumaCantidadLayout.setHorizontalGroup(
            jFrame_AdvertenciaSumaCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrame_AdvertenciaSumaCantidadLayout.setVerticalGroup(
            jFrame_AdvertenciaSumaCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evsim");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setForeground(java.awt.Color.white);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 100, 100));
        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(970, 870));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ConsumoE.setBackground(new java.awt.Color(255, 255, 255));
        ConsumoE.setText("CONSUMO DE ENERGIA (KWH)POR TECNOLOGIA");
        ConsumoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsumoEActionPerformed(evt);
            }
        });

        ImpactoCurva.setBackground(new java.awt.Color(255, 255, 255));
        ImpactoCurva.setText("IMPACTO EN LA CURVA DE CARGA - BARRIO  \"LOS CEDRITOS\"");
        ImpactoCurva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpactoCurvaActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DatosSalida.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImpactoCurva)
                            .addComponent(ConsumoE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(ConsumoE)
                .addGap(7, 7, 7)
                .addComponent(ImpactoCurva)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel9.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DatosEntrada.png"))); // NOI18N

        jLabel8.setText("CANTIDAD DE VEHICULOS");

        jLabel9.setText("AÑO DE SIMULACIÓN");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("PHEV");

        jLabel11.setText("BEV");

        jLabel13.setText("TIPOS DE EV");

        jLabel18.setText("CANTIDAD");

        Cantidad_PHEV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        Cantidad_BEV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        Cantidad_PHEV1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        Cantidad_BEV1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        jLabel14.setText("TIPOS DE USUARIO");

        TiposUSR_PHEV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trabajador Normal", "Trabajador 12 horas", "Ama de  Casa", "Trabajador2 Jornadas", "Trabajador de  Noche" }));

        TiposUSR_BEV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trabajador Normal", "Trabajador 12 horas", "Ama de  Casa", "Trabajador2 Jornadas", "Trabajador de  Noche" }));

        TiposEV_PHEV1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chevrolet" }));

        TiposEV_BEV1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nissan", "Renault" }));

        TiposEV_BEV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Renault" }));
        TiposEV_BEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiposEV_BEVActionPerformed(evt);
            }
        });

        TiposEV_PHEV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toyota" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TiposEV_PHEV1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TiposEV_BEV1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TiposEV_BEV, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TiposEV_PHEV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cantidad_PHEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cantidad_BEV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cantidad_PHEV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cantidad_BEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(TiposUSR_PHEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(TiposUSR_BEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(54, 54, 54))))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(Cantidad_PHEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cantidad_PHEV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(Cantidad_BEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(Cantidad_BEV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(TiposEV_PHEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TiposEV_PHEV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TiposEV_BEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TiposEV_BEV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TiposUSR_PHEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(TiposUSR_BEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        jTextField1_anioSimular.setText("2014");

        jSlider3_anioSimulacion.setBackground(new java.awt.Color(255, 255, 255));
        jSlider3_anioSimulacion.setMajorTickSpacing(1);
        jSlider3_anioSimulacion.setMaximum(2033);
        jSlider3_anioSimulacion.setMinimum(2014);
        jSlider3_anioSimulacion.setMinorTickSpacing(1);
        jSlider3_anioSimulacion.setPaintTicks(true);
        jSlider3_anioSimulacion.setSnapToTicks(true);
        jSlider3_anioSimulacion.setToolTipText("");
        jSlider3_anioSimulacion.setValue(1);
        jSlider3_anioSimulacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSlider3_anioSimulacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3_anioSimulacionStateChanged(evt);
            }
        });

        jSlider2_CantidadVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        jSlider2_CantidadVehiculos.setMajorTickSpacing(1);
        jSlider2_CantidadVehiculos.setMaximum(1);
        jSlider2_CantidadVehiculos.setMinorTickSpacing(1);
        jSlider2_CantidadVehiculos.setValue(0);
        jSlider2_CantidadVehiculos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2_CantidadVehiculosStateChanged(evt);
            }
        });

        jTextField13_CantidadVehiculos.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jSlider2_CantidadVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13_CantidadVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jSlider3_anioSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jTextField1_anioSimular, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSlider3_anioSimulacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jTextField1_anioSimular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSlider2_CantidadVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jTextField13_CantidadVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton4_GraficarMatlab.setText("GRAFICO DE MATLAB");
        jButton4_GraficarMatlab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_GraficarMatlabActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CasoSimular.png"))); // NOI18N

        jCheckBox_CasoSimular.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox_CasoSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_CasoSimularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_CasoSimular)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox_CasoSimular))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EscudoUnal.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Titulo.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Esenario_ImpactoAmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TendenciaCrecimiento.png"))); // NOI18N

        jSlider4_anioImpactoAmbiental.setBackground(new java.awt.Color(255, 255, 255));
        jSlider4_anioImpactoAmbiental.setMajorTickSpacing(1);
        jSlider4_anioImpactoAmbiental.setMaximum(2033);
        jSlider4_anioImpactoAmbiental.setMinimum(2014);
        jSlider4_anioImpactoAmbiental.setMinorTickSpacing(1);
        jSlider4_anioImpactoAmbiental.setPaintTicks(true);
        jSlider4_anioImpactoAmbiental.setSnapToTicks(true);
        jSlider4_anioImpactoAmbiental.setToolTipText("");
        jSlider4_anioImpactoAmbiental.setValue(1);
        jSlider4_anioImpactoAmbiental.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSlider4_anioImpactoAmbiental.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4_anioImpactoAmbientalStateChanged(evt);
            }
        });

        Tiempo_ImpactoAmb.setText("2014");
        Tiempo_ImpactoAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tiempo_ImpactoAmbActionPerformed(evt);
            }
        });

        BottonImpactoAmb.setText("GENERAR SIMULACIÓN");
        BottonImpactoAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonImpactoAmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(Esenario_ImpactoAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tiempo_ImpactoAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSlider4_anioImpactoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(BottonImpactoAmb)
                                .addGap(47, 47, 47))))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addComponent(jSlider4_anioImpactoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Esenario_ImpactoAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tiempo_ImpactoAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BottonImpactoAmb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo1.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(85, 85, 85)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jButton4_GraficarMatlab)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4_GraficarMatlab)
                        .addGap(126, 126, 126))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(420, 420, 420))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu3.setText("jMenu3");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-959)/2, (screenSize.height-713)/2, 959, 713);
    }// </editor-fold>//GEN-END:initComponents

    private void ImpactoCurvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpactoCurvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImpactoCurvaActionPerformed

    private void jSlider3_anioSimulacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3_anioSimulacionStateChanged
        try {
            
            String anio =Integer.toString(jSlider3_anioSimulacion.getValue());
            jTextField1_anioSimular.setText(anio);
            
             int i ,cantidad, m;
             m = Integer.parseInt(jTextField1_anioSimular.getText());
             int[] j = {100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121};
             
             cantidad =j[10];
             String anio1 =Integer.toString(m);
            jTextField1_anioSimular.setText(anio1);
            //PrcedimientosBD damecantidad = new PrcedimientosBD();
            //cantidad=damecantidad.NoVehoculosPorAnio(jTextField1.getText());
            jSlider2_CantidadVehiculos.setMaximum(cantidad);
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Panel_Principal_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jSlider3_anioSimulacionStateChanged

    private void jCheckBox_CasoSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CasoSimularActionPerformed
        
        jFrame_ImagenUsuarios.setSize(900, 400);
        jFrame_ImagenUsuarios.setLocationRelativeTo(null);
        jFrame_ImagenUsuarios.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_CasoSimularActionPerformed

    private void jButton4_GraficarMatlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_GraficarMatlabActionPerformed
       
        ProcedimientosMAtlab procedimientosMAtlab = new ProcedimientosMAtlab();
        //si la suma de todas las cantidades es igual entonces proceda a hacer la simulacion de lo contrario muestra un mensaje 
        if((Double.valueOf(Cantidad_PHEV.getSelectedItem().toString())+Double.valueOf(Cantidad_PHEV1.getSelectedItem().toString())+Double.valueOf(Cantidad_BEV.getSelectedItem().toString())+Double.valueOf(Cantidad_BEV1.getSelectedItem().toString())==Double.valueOf(jTextField13_CantidadVehiculos.getText()))){
            //Cantidad Vehiculos
            procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 5, 4, Double.valueOf(jTextField13_CantidadVehiculos.getText()));
            //Tipos de EV
            procedimientosMAtlab.writeExcelString(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 5, 1, TiposEV_PHEV.getSelectedItem().toString());
            procedimientosMAtlab.writeExcelString(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 6, 1, TiposEV_PHEV1.getSelectedItem().toString());
            procedimientosMAtlab.writeExcelString(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 7, 1, TiposEV_BEV.getSelectedItem().toString());
            procedimientosMAtlab.writeExcelString(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 8, 1, TiposEV_BEV1.getSelectedItem().toString());
            //Cantidad por usuario y vehiculo
            procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 5, 2, Double.valueOf(Cantidad_PHEV.getSelectedItem().toString()));
            procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 6, 2, Double.valueOf(Cantidad_PHEV1.getSelectedItem().toString()));
            procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 7, 2, Double.valueOf(Cantidad_BEV.getSelectedItem().toString()));
            procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 8, 2, Double.valueOf(Cantidad_BEV1.getSelectedItem().toString()));        
            //Tipos de Usuario
            procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 5, 3, Double.valueOf(TiposUSR_PHEV.getSelectedIndex()+1));
            procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 7, 3, Double.valueOf(TiposUSR_BEV.getSelectedIndex()+1));
            System.out.print(TiposUSR_BEV.getSelectedIndex());
            //variable de la salida0
            if(ConsumoE.isSelected()==true){
                procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 10, 1, 1.0);
                }
            else{
                procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 10, 1, 0.0);
            }
            if(ImpactoCurva.isSelected()==true){
                procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 11, 1, 1.0);
                }
            else{
                procedimientosMAtlab.writeExcel(System.getProperty("user.dir")+"/Vehiculos.xls", "Entrada", 11, 1, 0.0);
            }

            try {
                procedimientosMAtlab.prcedimiento0var(System.getProperty("user.dir")+"/curvacarga.exe");    

            } catch (IOException ex) {
                Logger.getLogger(Panel_Principal_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        else {
            jFrame_AdvertenciaSumaCantidad.setSize(371, 98);
            jFrame_AdvertenciaSumaCantidad.setLocationRelativeTo(null);
            jFrame_AdvertenciaSumaCantidad.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton4_GraficarMatlabActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jSlider2_CantidadVehiculosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2_CantidadVehiculosStateChanged

        String CantidadMax =Integer.toString(jSlider2_CantidadVehiculos.getValue());
       jTextField13_CantidadVehiculos.setText(CantidadMax); 
       int cantidad;
        cantidad=jSlider2_CantidadVehiculos.getValue();
        Cantidad_PHEV.removeAllItems();
        Cantidad_BEV.removeAllItems();
        Cantidad_PHEV1.removeAllItems();
        Cantidad_BEV1.removeAllItems();
        for ( int i=0;i <=cantidad;i=i+1){
                Cantidad_PHEV.addItem(Integer.toString(i));
                Cantidad_BEV.addItem(Integer.toString(i));
                Cantidad_PHEV1.addItem(Integer.toString(i));
                Cantidad_BEV1.addItem(Integer.toString(i));
           }
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2_CantidadVehiculosStateChanged

    private void ConsumoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsumoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsumoEActionPerformed

    private void jSlider4_anioImpactoAmbientalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4_anioImpactoAmbientalStateChanged

        try {
            
            String anio =Integer.toString(jSlider4_anioImpactoAmbiental.getValue());
            Tiempo_ImpactoAmb.setText(anio);
            
             int i ,cantidad, m;
             m = Integer.parseInt(Tiempo_ImpactoAmb.getText());
             int[] j = {100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121};
             
             cantidad =j[10];
             String anio1 =Integer.toString(m);
            Tiempo_ImpactoAmb.setText(anio1);
            //PrcedimientosBD damecantidad = new PrcedimientosBD();
            //cantidad=damecantidad.NoVehoculosPorAnio(jTextField1.getText());
           
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Panel_Principal_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider4_anioImpactoAmbientalStateChanged

    private void Tiempo_ImpactoAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tiempo_ImpactoAmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tiempo_ImpactoAmbActionPerformed

    private void BottonImpactoAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonImpactoAmbActionPerformed
        ProcedimientosMAtlab procedimientosMAtlab = new ProcedimientosMAtlab();
        procedimientosMAtlab.writeExcel(System.getProperty("user.dir") + "/Vehiculos.xls", "Entrada", 1, 0, Double.valueOf(Tiempo_ImpactoAmb.getText()));
        procedimientosMAtlab.writeExcel(System.getProperty("user.dir") + "/Vehiculos.xls", "Entrada", 1, 1, Double.valueOf(Esenario_ImpactoAmb.getSelectedIndex())+1.0);
        //procedimientosMAtlab.writeExcel(System.getProperty("user.dir") + "/Vehiculos.xls", "Entrada", 1, 1, Double.valueOf(Gasolina_ImpactoAmb.getSelectedIndex())+1.0);
        try {
            procedimientosMAtlab.prcedimiento0var(System.getProperty("user.dir")+"/Impacto.exe");    
            
        } catch (IOException ex) {
            Logger.getLogger(Panel_Principal_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //System.out.println(System.getProperty("user.dir") + "/Matlab");
        // TODO add your handling code here:
    }//GEN-LAST:event_BottonImpactoAmbActionPerformed

    private void TiposEV_BEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiposEV_BEVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiposEV_BEVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Panel_Principal_1.class.getName()).log(Level.SEVERE, null, ex);
        }        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
        public void run() {
                 
                new Panel_Principal_1().setVisible(true);
                
            }
        });
    }
    private int AumentaVehiculo=0;
    public String VectorVehiculos [];
    private List array_dinamico;
    public javax.swing.JPanel jPanel2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonImpactoAmb;
    private javax.swing.JComboBox Cantidad_BEV;
    private javax.swing.JComboBox Cantidad_BEV1;
    private javax.swing.JComboBox Cantidad_PHEV;
    private javax.swing.JComboBox Cantidad_PHEV1;
    private javax.swing.JCheckBox ConsumoE;
    private javax.swing.JComboBox Esenario_ImpactoAmb;
    private javax.swing.JCheckBox ImpactoCurva;
    private javax.swing.JTextField Tiempo_ImpactoAmb;
    private javax.swing.JComboBox TiposEV_BEV;
    private javax.swing.JComboBox TiposEV_BEV1;
    private javax.swing.JComboBox TiposEV_PHEV;
    private javax.swing.JComboBox TiposEV_PHEV1;
    private javax.swing.JComboBox TiposUSR_BEV;
    private javax.swing.JComboBox TiposUSR_PHEV;
    private javax.swing.JButton jButton4_GraficarMatlab;
    private javax.swing.JCheckBox jCheckBox_CasoSimular;
    private javax.swing.JFrame jFrame_AdvertenciaSumaCantidad;
    private javax.swing.JFrame jFrame_ImagenUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider2_CantidadVehiculos;
    private javax.swing.JSlider jSlider3_anioSimulacion;
    private javax.swing.JSlider jSlider4_anioImpactoAmbiental;
    private javax.swing.JTextField jTextField13_CantidadVehiculos;
    private javax.swing.JTextField jTextField1_anioSimular;
    // End of variables declaration//GEN-END:variables




public class Example5 {
   

    /**
     * The constructor of the class have to start joPAS to run Octave because
     * Octave program takes a long time to start
     */
    public Example5() {
        
    }
}

}
